name: Build/Deploy to GitHub Pages

on:
  push:
    branches: [add-gha-deploy-workflow]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4

    - name: Install pygbag
      run: pip install pygbag

    - name: Build with pygbag
      run: pygbag pacman.py

    - name: Copy assets to build folder
      run: |
        mkdir -p build/web/assets
        cp -r assets/* build/web/assets/

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/web
